### ISSUE TITLE
Not sure how -d is supposed to work

### ISSUE THREAD

**Issue by kshehadeh** [IanS5/simplify#1]
Could you give an example in the readme or --help on how to use the -d argument?   I tried this but got an error:

    ./simplify -d ADD2S="(2+2)" "ADD2S + 4"

and got this error:

    simplify: expected an expression in the form of VARIABLE=EXPRESSION

Probably because there's a number in the variable name.   So I removed that and got this: 

    /simplify -d ADD="(2+2)" "ADD + 4"

And got this:

    2 + 2 = 4
    2 + 2 + 4

So I guess the first one evaluates the variable expression and the second is just a replacement/simplification of the last expression.

Is that right?

**Comment by IanS5** [comment]
It definitely shouldn't be printing that first line. I when was the last time you pulled the repo? I think this was just fixed a few hours ago commit d75eb1bdab62e24dca69011168e12ba5345ab8ab
