### ISSUE TITLE
Wrong sign for -x = 1

### ISSUE THREAD

**Issue by tavianator** [IanS5/simplify#2]
$ ./simplify --isolate x '(0 - x) = 1'
    x = 1

But really, it should be `x = -1`

**Comment by IanS5** [comment]
Looks like it's a problem with the `_expression_isolate_variable_recursive` function, it assumes all operator's operands are reversible. I'm working on a fix for this with #3. Still got to write tests for expressions like `0 - x = 1` before it's merged. I'll get around to it later this evening

**Comment by IanS5** [comment]
fixed in #3
